spring:
  datasource:
    url: jdbc:sqlite:data.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        cache:
          use-second-level-cache: false
mybatis:
  configuration:
    cache-enabled: false
    local-cache-scope: STATEMENT


server:
  port: 34740
  servlet:
    session:
      timeout: 680400

wzry:
  api: http://192.168.1.11:8080

report:
  bid: 291841860
  gid: 1041541077

logging:
  pattern:
    console: "%clr([%thread]){blue} %clr(%-32.32logger{32}){magenta} %clr(%d{yyyy-MM-dd HH:mm:ss}){red} %clr(%-5p): %msg%n"
    file: "[%thread] %-32.32logger{32} %d{yyyy-MM-dd HH:mm:ss} %-5p: %msg%n"
  file:
    # 输出的log文件名
    name: ./logs/slf4j.log
    # 输出的文件的路径
    path: logs
    # 限制日志文件的大小
    max-size: 10MB
    # 日志的保存天数
    max-history: 7
  level:
    root: info
    org.quartz.impl.StdSchedulerFactory: error
    org.quartz.core.QuartzScheduler: error
    org.quartz.core.SchedulerSignalerImpl: error
    org.quartz.simpl.RAMJobStore: error