spring:
  datasource:
    url: jdbc:sqlite:data.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        cache:
          use-second-level-cache: false
  redis:
    host: 127.0.0.1
    port: 6379
    database: 5
    timeout: 60000
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

mybatis:
  configuration:
    cache-enabled: false
    local-cache-scope: STATEMENT


server:
  port: 34740
  servlet:
    session:
      timeout: 680400

wzry:
  api: http://119.45.132.231:8080

report:
  point-gid: 943648151
  bid: 291841860
  gid: 1041541077

logging:
  pattern:
    console: "%clr([%thread]){blue} %clr(%-32.32logger{32}){magenta} %clr(%d{yyyy-MM-dd HH:mm:ss}){red} %clr(%-5p): %msg%n"
    file: "[%thread] %-32.32logger{32} %d{yyyy-MM-dd HH:mm:ss} %-5p: %msg%n"
  file:
    name: ./logs/slf4j.log
    path: logs
  level:
    root: info
    org.quartz.impl.StdSchedulerFactory: error
    org.quartz.core.QuartzScheduler: error
    org.quartz.core.SchedulerSignalerImpl: error
    org.quartz.simpl.RAMJobStore: error
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7